_target_: lightning.pytorch.loggers.WandbLogger
project: Thesis-Research-Diffusion
save_dir: "/data/.cache/"
name: ""
settings:
  _target_: wandb.Settings
  _disable_stats: true
  _disable_meta: true
offline: false