_target_: lightning.pytorch.loggers.WandbLogger
project: Thesis-Research
save_dir: "../logs"
log_model: false
settings:
  _target_: wandb.Settings
  _disable_stats: true
  _disable_meta: true
offline: false