_target_: lightning.pytorch.loggers.WandbLogger
project: Thesis-Research
save_dir: "/data/.cache/"
name: "scc_v5-10000-filtered-v4"
settings:
  _target_: wandb.Settings
  _disable_stats: true
  _disable_meta: true
offline: false