defaults:
  - model@models.unet:  scc_v5 # diffusers_native
  - data: bfscc_filtered
  - scheduler@training.scheduler: ddim
  - scheduler@inference.scheduler: ddim
  - logger: wandb
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: ./

resume_from_checkpoint: null

pl_trainer:
  accelerator: gpu
  num_nodes: 1
  benchmark: true
  precision: "16-mixed"
  strategy: ddp
  num_sanity_val_steps: 0
  max_epochs: ${training.epochs}
  enable_model_summary: true
  log_every_n_steps: 10
  check_val_every_n_epoch: 10
  devices: 2

models:
  unet:
    sample_size: ${data.image_resolution}

data:
  image_resolution: 512
  batch_size: ${training.batch_size}
  num_images: 10000

inference:
  num_samples: 128
  scheduler:
    clip_sample: true
  pipeline_kwargs:
    batch_size: 8
    num_inference_steps: 25

training:
  batch_size: 4
  learning_rate: 1.e-4
  epochs: 350
  ema_decay: 0.9999 # `-1` disables it